import type { Lead } from "@/types/crm";

export const sampleLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Dana Whitfield",
    company: "Northwind Studio",
    email: "dana@northwind.studio",
    stage: "qualified",
    value: 12000,
    source: "Referral",
    nextAction: "Send scoped proposal",
    lastContactedAt: "2026-05-28",
    createdAt: "2026-05-10",
    updatedAt: "2026-05-28"
  },
  {
    id: "lead-2",
    name: "Marcus Lee",
    company: "Brightpath Logistics",
    email: "m.lee@brightpath.co",
    stage: "proposal",
    value: 28500,
    source: "Outbound",
    nextAction: "Follow up on pricing questions",
    lastContactedAt: "2026-05-30",
    createdAt: "2026-04-22",
    updatedAt: "2026-05-30"
  },
  {
    id: "lead-3",
    name: "Priya Nair",
    company: "Cedar & Co",
    email: "priya@cedarandco.com",
    stage: "new",
    value: 6400,
    source: "Website",
    nextAction: "Qualify budget and timeline",
    lastContactedAt: "2026-05-31",
    createdAt: "2026-05-29",
    updatedAt: "2026-05-31"
  },
  {
    id: "lead-4",
    name: "Tomas Berg",
    company: "Atlas Fabrication",
    email: "tomas@atlasfab.io",
    stage: "won",
    value: 41000,
    source: "Referral",
    nextAction: "Kickoff scheduled",
    lastContactedAt: "2026-05-26",
    createdAt: "2026-03-18",
    updatedAt: "2026-05-26"
  },
  {
    id: "lead-5",
    name: "Aisha Rahman",
    company: "Lumen Health",
    email: "aisha@lumenhealth.org",
    stage: "qualified",
    value: 18750,
    source: "Event",
    nextAction: "Book technical review",
    lastContactedAt: "2026-05-12",
    createdAt: "2026-04-30",
    updatedAt: "2026-05-12"
  },
  {
    id: "lead-6",
    name: "Greg Olsen",
    company: "Pier 9 Retail",
    email: "greg@pier9.shop",
    stage: "new",
    value: 5200,
    source: "Outbound",
    nextAction: "Confirm decision maker",
    lastContactedAt: "2026-05-09",
    createdAt: "2026-05-06",
    updatedAt: "2026-05-09"
  },
  {
    id: "lead-7",
    name: "Helena Cruz",
    company: "Verde Interiors",
    email: "helena@verde.design",
    stage: "proposal",
    value: 22300,
    source: "Website",
    nextAction: "Review contract redlines",
    lastContactedAt: "2026-05-29",
    createdAt: "2026-04-11",
    updatedAt: "2026-05-29"
  },
  {
    id: "lead-8",
    name: "Owen Park",
    company: "Hatchet Outdoors",
    email: "owen@hatchet.gear",
    stage: "lost",
    value: 9800,
    source: "Event",
    nextAction: "Revisit next quarter",
    lastContactedAt: "2026-05-04",
    createdAt: "2026-03-30",
    updatedAt: "2026-05-04"
  },
  {
    id: "lead-9",
    name: "Sofia Marchetti",
    company: "Riverside Dental",
    email: "sofia@riversidedental.care",
    stage: "qualified",
    value: 14600,
    source: "Referral",
    nextAction: "Share implementation timeline",
    lastContactedAt: "2026-05-31",
    createdAt: "2026-05-15",
    updatedAt: "2026-05-31"
  },
  {
    id: "lead-10",
    name: "Daniel Okafor",
    company: "Summit Analytics",
    email: "daniel@summit.ai",
    stage: "won",
    value: 33500,
    source: "Outbound",
    nextAction: "Onboarding in progress",
    lastContactedAt: "2026-05-20",
    createdAt: "2026-02-27",
    updatedAt: "2026-05-20"
  }
];
