import type { Listing } from "@/types/marketplace";

export const sampleListings: Listing[] = [
  {
    id: "listing-1",
    title: "Weekend deep-clean for homes",
    description: "Detailed two-person cleaning crew for apartments and houses up to 3 bedrooms. Supplies included.",
    category: "Cleaning",
    priceLabel: "From $120 / visit",
    priceValue: 120,
    location: "Riverside",
    rating: 4.8,
    sellerId: "seller-1",
    sellerName: "Maria's Cleaning Co",
    responseTime: "Replies in ~2h",
    verified: true,
    tags: ["home", "recurring"]
  },
  {
    id: "listing-2",
    title: "Licensed electrician — small jobs",
    description: "Outlets, fixtures, panel checks, and EV charger installs. Fully insured and permit-ready.",
    category: "Home Repair",
    priceLabel: "$95 / hour",
    priceValue: 95,
    location: "Eastgate",
    rating: 4.9,
    sellerId: "seller-2",
    sellerName: "Bolt Electric",
    responseTime: "Replies in ~1h",
    verified: true,
    tags: ["licensed", "urgent"]
  },
  {
    id: "listing-3",
    title: "Personal trainer — outdoor sessions",
    description: "Strength and mobility coaching at local parks. First session free for new clients.",
    category: "Fitness",
    priceLabel: "$55 / session",
    priceValue: 55,
    location: "Highland Park",
    rating: 4.7,
    sellerId: "seller-3",
    sellerName: "Coach Devon",
    responseTime: "Replies in ~4h",
    verified: false,
    tags: ["outdoor", "1-on-1"]
  },
  {
    id: "listing-4",
    title: "Wedding & event photography",
    description: "Half and full-day coverage with a 48-hour preview gallery. Second shooter available.",
    category: "Photography",
    priceLabel: "From $850 / event",
    priceValue: 850,
    location: "Downtown",
    rating: 5.0,
    sellerId: "seller-4",
    sellerName: "Aperture Studio",
    responseTime: "Replies in ~6h",
    verified: true,
    tags: ["events", "premium"]
  },
  {
    id: "listing-5",
    title: "Math & science tutoring (grades 6–12)",
    description: "Personalized tutoring in algebra, geometry, chemistry, and physics. Online or in-person.",
    category: "Tutoring",
    priceLabel: "$40 / hour",
    priceValue: 40,
    location: "Westfield",
    rating: 4.6,
    sellerId: "seller-5",
    sellerName: "BrightMind Tutors",
    responseTime: "Replies in ~3h",
    verified: false,
    tags: ["students", "online"]
  },
  {
    id: "listing-6",
    title: "Same-day furniture assembly",
    description: "Flat-pack and custom furniture assembled fast. Tools, hauling, and cleanup included.",
    category: "Home Repair",
    priceLabel: "From $60 / job",
    priceValue: 60,
    location: "Eastgate",
    rating: 4.5,
    sellerId: "seller-6",
    sellerName: "Hex & Allen",
    responseTime: "Replies in ~30m",
    verified: true,
    tags: ["same-day", "moving"]
  },
  {
    id: "listing-7",
    title: "Dog walking & drop-in visits",
    description: "Bonded, insured walkers for daily or one-off visits. GPS-tracked routes and photo updates.",
    category: "Pet Care",
    priceLabel: "$25 / walk",
    priceValue: 25,
    location: "Riverside",
    rating: 4.9,
    sellerId: "seller-7",
    sellerName: "Happy Tails",
    responseTime: "Replies in ~1h",
    verified: true,
    tags: ["pets", "daily"]
  },
  {
    id: "listing-8",
    title: "Brand & logo design sprint",
    description: "One-week branding sprint: logo, palette, and a mini style guide. Two revision rounds.",
    category: "Design",
    priceLabel: "From $600 / project",
    priceValue: 600,
    location: "Remote",
    rating: 4.8,
    sellerId: "seller-8",
    sellerName: "North Studio",
    responseTime: "Replies in ~5h",
    verified: false,
    tags: ["branding", "remote"]
  }
];
